### ISSUE TITLE
cygpath: not found

### ISSUE THREAD

**Issue by Rudloff** [Dagger0/IPvFox#12]
On Linux, I get this error when building:
(cygpath -aw ext/ || echo `pwd`/ext/) > build/ipvfox@dagger2-addons.mozilla.org
/bin/sh: 1: cygpath: not found

The build still works but I think it would be better to test if Cygwin is used or not.

**Comment by Dagger0** [comment]
I've made it test with `which` in c672973a575348ae2c31542342f25977b5d4acee.
